# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Learn SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Learn SwiftUI
  pod 'Kingfisher', '~> 5.8.2'

  target 'Learn SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
